spring:
  profiles: peer1

server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
    register-with-eureka: false
    fetch-registry: false

